name = "RounDeck"
version = "1.0.0"
link = "https://github.com/ZeroPoke/crankshaft-roundeck"
source = "https://github.com/ZeroPoke/crankshaft-roundeck"
min-crankshaft-version = "0.2.2"

[author]
name = "ZeroPoke"
link = "https://github.com/ZeroPoke/"

[entrypoints]

	[entrypoints.desktop]
	library = true
	menu = true

	[entrypoints.deck]
	library = true
	menu = true
	quick-access = true

[store]
description = """
Rounds the Edges of most things.  Pretty much just a port of EMERALD0874 work.  https://github.com/EMERALD0874
"""